# Install script for directory: /home/christoph/scribus15svn/trunk/Scribus/doc/en/images

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/opt/scribus-exp")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Debug")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/doc/scribus-1.5.0.svn/en/images" TYPE FILE FILES
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/krita1.jpg"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_shortwords.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/RDF.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefsdisplay.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/before_short_words.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab7b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt16.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt19.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gsadv3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/monprof2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/geometry1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/printseps.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/SwB.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_pdfexport.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager1b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt17.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/context_image.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/formularz_js_skrypt.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontsampler2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pdfxintent.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/xnview.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontpref1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab9.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/colormanager2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt10.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefsblgrid1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/lilyp.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_typog.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/printpreview.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/node_edit_close.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_colormgmt.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/shapes7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_magazine.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Cover_en1-page1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/lprof.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab10.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pdfxcolor.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/colormgmtscreen.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/context_shape.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/swdialog.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_new_report2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/plot2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/frame_shape_flow.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/toolbar1d.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/boundingbox1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/layers2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gsadv1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/svg1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/htmlstyle.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pdfeffect1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/cups2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_keyboard.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fonts.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/layers1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/scribuscms1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/nodes_edit.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_exttools.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/monprof3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_document.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/boundingbox.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acro2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gimpoptions3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/edit_shapes.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/docheader1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pstoedit1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/printer2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/monprof4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_goldenmean.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/ooeps1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab11.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/external.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/after_short_words.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/povray.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acro1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text-frame-link.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gsadv2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontpref2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_9parts.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/skewing.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt15.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_fibonacci.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/XYZ_Prop1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/toolbar3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Scripter_error_string.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_signup.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager3b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/inkscape.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_guides.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/formularz_js_sprawdzanie.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefsgeneral.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pagetemplate1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs10.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/cmsmodify1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Scripter.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab12.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/scribus2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_display.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_filter136b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs15.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_misc.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fonts3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acroinfo.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text-frame-unlink.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prop_shape.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_new_report3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt11.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt14.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/contourline_flow.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs11.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_general.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/formularz_export_PDF.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/result.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf-error1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_filter135.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pdfeffect2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acro3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_my_view.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontsampler.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/symbole.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_preflight.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/formularz_pole_num.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/imageeffects.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/geometry.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pdfx3-1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt17a.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/ulica.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/siatka_jednostki_miar.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager10.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/toolbar1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/context_text135.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_flow.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/plot1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontpref3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/oochart.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt20.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/printer3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/hyphen3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acroreader5.1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_gutenberg.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/ksnapshot.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_guides1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontprev.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt21.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gammagrayscale.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_filter136.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_linking.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/docheader2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/colormanager1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf-error2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontpref4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs12.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/oogettext1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/hyphen1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/scribustru4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/squat_tux.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acrosec.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/batik1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fonts2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fontmatrix.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt12.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/monprof1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Image_Properties.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/printer1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/polygons1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_pdfexport1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/fonts4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt18b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/acropass.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_new_report1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab7a.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/polygons.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/pagenumbering.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/wlasciwosci_pola.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gimpoptions1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/shapes8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt9.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/swmenu.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/siatka_menu.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager9.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/hyphen2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/XYZ_Prop.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs-mac-1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/round_rectangle.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/wyslij_formularz.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/spinbox1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/docinfo2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt6.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_document1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Rembrandt18.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/style_manager7.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab8.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/formularz_nowy.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/cups1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/rf-error3.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/gimpoptions2.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/combine_polygons4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab13.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/prefs_tools1.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/kfontinstaller.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab4.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/htmlimport.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/automargins.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/text_tab11b.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/line_tab5.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/shape_edit.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/docinfo.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/Mantis_searching.png"
    "/home/christoph/scribus15svn/trunk/Scribus/doc/en/images/DrawLatexFrame.png"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

