######################################################################
# Automatically generated by qmake (3.1) Tue Sep 1 21:45:47 2020
######################################################################

INCLUDEPATH+=./scribus
TEMPLATE = subdirs

# Directories
SUBDIRS += Scribus.pro
