
#define SCRIBUS_VERSION_MAJOR 1
#define SCRIBUS_VERSION_MINOR 7
#define SCRIBUS_VERSION_MICRO 1
#define SCRIBUS_VERSION_TWEAK 0
#define SCRIBUS_VERSION_EXTRA ""

#define SCRIBUS_VERSION_STRING "1.7.1"
#define SCRIBUS_FULL_VERSION_STRING "1.7.1"

#define SCRIBUS_LEGAL_COPYRIGHT "Copyright (C) 2001-2025 by The Scribus Team"
