
#define SCRIBUS_VERSION_MAJOR 1
#define SCRIBUS_VERSION_MINOR 7
#define SCRIBUS_VERSION_MICRO 2
#define SCRIBUS_VERSION_TWEAK 0
#define SCRIBUS_VERSION_EXTRA ".svn"

#define SCRIBUS_VERSION_STRING "1.7.3"
#define SCRIBUS_FULL_VERSION_STRING "1.7.3.svn"

#define SCRIBUS_LEGAL_COPYRIGHT "Copyright (C) 2001-2026 by The Scribus Team"
