
#define SCRIBUS_VERSION_MAJOR 1
#define SCRIBUS_VERSION_MINOR 6
#define SCRIBUS_VERSION_MICRO 6
#define SCRIBUS_VERSION_TWEAK 0
#define SCRIBUS_VERSION_EXTRA ".svn"

#define SCRIBUS_VERSION_STRING "1.6.6"
#define SCRIBUS_FULL_VERSION_STRING "1.6.6.svn"

#define SCRIBUS_LEGAL_COPYRIGHT "Copyright (C) 2001-2026 by The Scribus Team"
