
#define SCRIBUS_VERSION_MAJOR 1
#define SCRIBUS_VERSION_MINOR 6
#define SCRIBUS_VERSION_MICRO 5
#define SCRIBUS_VERSION_TWEAK 0
#define SCRIBUS_VERSION_EXTRA ""

#define SCRIBUS_VERSION_STRING "1.6.5"
#define SCRIBUS_FULL_VERSION_STRING "1.6.5"

#define SCRIBUS_LEGAL_COPYRIGHT "Copyright (C) 2001-2026 by The Scribus Team"
