
//Syntax: ATTRDEF( datatype, gettername, name, defaultvalue)

ATTRDEF(int, fontSize, FontSize, 10)
ATTRDEF(int, fillShade, FillShade, 100)
ATTRDEF(int, strokeShade, StrokeShade, 100)
ATTRDEF(StyleFlag, effects, Effects, ScStyle_Default)
ATTRDEF(int, scaleH, ScaleH, 1000)
ATTRDEF(int, scaleV, ScaleV, 1000)
ATTRDEF(int, baselineOffset, BaselineOffset, 0)
ATTRDEF(int, shadowXOffset, ShadowXOffset, 0)
ATTRDEF(int, shadowYOffset, ShadowYOffset, 0)
ATTRDEF(int, outlineWidth, OutlineWidth, 0)
ATTRDEF(int, underlineOffset, UnderlineOffset, 0)
ATTRDEF(int, underlineWidth, UnderlineWidth, 0)
ATTRDEF(int, strikethruOffset, StrikethruOffset, 0)
ATTRDEF(int, strikethruWidth, StrikethruWidth, 0)
ATTRDEF(int, tracking, Tracking, 0)
ATTRDEF(QString, fillColor, FillColor, "black")
ATTRDEF(QString, strokeColor, StrokeColor, "black")
ATTRDEF(QString, language, Language, "")
ATTRDEF(ScFace, font, Font, ScFace::none())
